<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="13" passed="11" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-21T17:31:06 GST" name="PetStore API Test Suite" finished-at="2024-10-21T17:31:27 GST" duration-ms="21151">
    <groups>
    </groups>
    <test started-at="2024-10-21T17:31:06 GST" name="Pet API Tests" finished-at="2024-10-21T17:31:14 GST" duration-ms="8515">
      <class name="Api_Tests.Pet_Tests">
        <test-method signature="createPet()[pri:0, instance:Api_Tests.Pet_Tests@34129c78]" started-at="2024-10-21T17:31:06 GST" name="createPet" finished-at="2024-10-21T17:31:10 GST" duration-ms="3729" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPet -->
        <test-method signature="getPets()[pri:0, instance:Api_Tests.Pet_Tests@34129c78]" started-at="2024-10-21T17:31:10 GST" name="getPets" finished-at="2024-10-21T17:31:11 GST" duration-ms="1390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPets -->
        <test-method signature="updatePet()[pri:0, instance:Api_Tests.Pet_Tests@34129c78]" started-at="2024-10-21T17:31:11 GST" name="updatePet" finished-at="2024-10-21T17:31:12 GST" depends-on-methods="Api_Tests.Pet_Tests.createPet" duration-ms="1277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updatePet -->
        <test-method signature="deletePet()[pri:0, instance:Api_Tests.Pet_Tests@34129c78]" started-at="2024-10-21T17:31:12 GST" name="deletePet" finished-at="2024-10-21T17:31:14 GST" depends-on-methods="Api_Tests.Pet_Tests.updatePet" duration-ms="2034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePet -->
      </class> <!-- Api_Tests.Pet_Tests -->
    </test> <!-- Pet API Tests -->
    <test started-at="2024-10-21T17:31:14 GST" name="Store API Tests" finished-at="2024-10-21T17:31:20 GST" duration-ms="6020">
      <class name="Api_Tests.Store_Tests">
        <test-method signature="getInventory()[pri:0, instance:Api_Tests.Store_Tests@723e88f9]" started-at="2024-10-21T17:31:14 GST" name="getInventory" finished-at="2024-10-21T17:31:15 GST" duration-ms="1044" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> but was <500>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <500>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at Api_Tests.Store_Tests.getInventory(Store_Tests.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getInventory -->
        <test-method signature="placeOrder()[pri:0, instance:Api_Tests.Store_Tests@723e88f9]" started-at="2024-10-21T17:31:15 GST" name="placeOrder" finished-at="2024-10-21T17:31:17 GST" duration-ms="1475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method signature="getOrderById()[pri:0, instance:Api_Tests.Store_Tests@723e88f9]" started-at="2024-10-21T17:31:17 GST" name="getOrderById" finished-at="2024-10-21T17:31:18 GST" depends-on-methods="Api_Tests.Store_Tests.placeOrder" duration-ms="1405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getOrderById -->
        <test-method signature="deleteOrder()[pri:0, instance:Api_Tests.Store_Tests@723e88f9]" started-at="2024-10-21T17:31:18 GST" name="deleteOrder" finished-at="2024-10-21T17:31:20 GST" depends-on-methods="Api_Tests.Store_Tests.getOrderById" duration-ms="2085" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteOrder -->
      </class> <!-- Api_Tests.Store_Tests -->
    </test> <!-- Store API Tests -->
    <test started-at="2024-10-21T17:31:20 GST" name="User API Tests" finished-at="2024-10-21T17:31:27 GST" duration-ms="6577">
      <class name="Api_Tests.User_Tests">
        <test-method signature="createUser()[pri:0, instance:Api_Tests.User_Tests@352ff4da]" started-at="2024-10-21T17:31:20 GST" name="createUser" finished-at="2024-10-21T17:31:21 GST" duration-ms="1049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method signature="getUserByUsername()[pri:0, instance:Api_Tests.User_Tests@352ff4da]" started-at="2024-10-21T17:31:21 GST" name="getUserByUsername" finished-at="2024-10-21T17:31:22 GST" depends-on-methods="Api_Tests.User_Tests.createUser" duration-ms="1028" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserByUsername -->
        <test-method signature="updateUser()[pri:0, instance:Api_Tests.User_Tests@352ff4da]" started-at="2024-10-21T17:31:22 GST" name="updateUser" finished-at="2024-10-21T17:31:23 GST" depends-on-methods="Api_Tests.User_Tests.getUserByUsername" duration-ms="988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUser -->
        <test-method signature="validateUpdatedUser()[pri:0, instance:Api_Tests.User_Tests@352ff4da]" started-at="2024-10-21T17:31:23 GST" name="validateUpdatedUser" finished-at="2024-10-21T17:31:25 GST" depends-on-methods="Api_Tests.User_Tests.updateUser" duration-ms="1353" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUpdatedUser -->
        <test-method signature="deleteUser()[pri:0, instance:Api_Tests.User_Tests@352ff4da]" started-at="2024-10-21T17:31:25 GST" name="deleteUser" finished-at="2024-10-21T17:31:27 GST" depends-on-methods="Api_Tests.User_Tests.validateUpdatedUser" duration-ms="2146" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <404> but was <500>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <404> but was <500>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at Api_Tests.User_Tests.deleteUser(User_Tests.java:147)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- Api_Tests.User_Tests -->
    </test> <!-- User API Tests -->
  </suite> <!-- PetStore API Test Suite -->
</testng-results>
